
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SYSTEM = 6;
  public static final int LBRACE = 2;
  public static final int ACTI = 12;
  public static final int COLON = 4;
  public static final int NUMBER = 14;
  public static final int GUARD = 11;
  public static final int EQUAL = 5;
  public static final int EOF = 0;
  public static final int ID = 13;
  public static final int error = 1;
  public static final int DEST = 10;
  public static final int STATE = 7;
  public static final int TRANSITION = 8;
  public static final int RBRACE = 3;
  public static final int SOURCE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "COLON",
  "EQUAL",
  "SYSTEM",
  "STATE",
  "TRANSITION",
  "SOURCE",
  "DEST",
  "GUARD",
  "ACTI",
  "ID",
  "NUMBER"
  };
}

